import type { Metadata } from "next";
import localFont from "next/font/local";

import Header from "@/features/header/components/Header";
import GlobalModal from "@/features/modal/components/GlobalModal";
import BottomNavigation from "@/features/navigation/components/BottomNavigation";
import Page from "@/shared/components/Page";

import "./ui/globals.css";

const geistSans = localFont({
  src: "./ui/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./ui/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <GlobalModal>
          <div>123</div>
        </GlobalModal>
        <Header />
        <main
          style={{
            margin: "50px",
            display: "flex",
            justifyContent: "center",
            overflow: "auto",
          }}
        >
          <Page>{children}</Page>
        </main>
        <BottomNavigation />
        {/* <footer className={styles.footer}>@luckylooky2</footer> */}
      </body>
    </html>
  );
}
