import type { Metadata } from "next";
import localFont from "next/font/local";

import Header from "@/features/header/components/Header";
import BottomNavigation from "@/features/navigation/components/BottomNavigation";

import "./ui/globals.css";
import styles from "./ui/page.module.css";

const geistSans = localFont({
  src: "./ui/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./ui/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        <div className={styles.page}>
          <main className={styles.main}>{children}</main>
        </div>
        <BottomNavigation />
        <footer className={styles.footer}>Footer</footer>
      </body>
    </html>
  );
}
